Publishing ZHE 4.0.0
ZenHubHQ/zenhub-enterprise pull request #46
Opened 2023-09-07 22:27 UTC by cwarje

Zenhub Enterprise 4.0.0 Release

- Zenhub platform
- Improved onboarding experience
- Board enhancements
- Integrations
- Productivity insights
- Security patches
- K3s, Redis, and Fluentd upgrades

2023-09-07 22:39 UTC, m62534 commented on k8s-cluster/base/non-dynamic/set-raptor-buckets-vars.yaml
> +            # FIXME - Using this hack from the past until we implement a better way. See base/non-dynamic/set-toad-buckets-vars.yaml
we can omit this for this repo

2023-09-07 22:39 UTC, m62534 commented on k8s-cluster/base/non-dynamic/set-raptor-buckets-vars.yaml
> +                  name: toad # Until we add this to the configuration secret - file upload/download move to raptor is in progress on Cloud still
can omit comments

2023-09-07 22:39 UTC, m62534 commented on k8s-cluster/base/non-dynamic/set-raptor-buckets-vars.yaml
> +            # - name: FILES_UPLOAD_PATH # TODO - Determine what this needs to be with Backend team help
comment omit here too

2023-09-07 22:45 UTC, cwarje commented on k8s-cluster/base/non-dynamic/set-raptor-buckets-vars.yaml
> +            # FIXME - Using this hack from the past until we implement a better way. See base/non-dynamic/set-toad-buckets-vars.yaml
Removed

2023-09-07 22:46 UTC, cwarje commented on k8s-cluster/base/non-dynamic/set-raptor-buckets-vars.yaml
> +                  name: toad # Until we add this to the configuration secret - file upload/download move to raptor is in progress on Cloud still
Removed

2023-09-07 22:46 UTC, cwarje commented on k8s-cluster/base/non-dynamic/set-raptor-buckets-vars.yaml
> +            # - name: FILES_UPLOAD_PATH # TODO - Determine what this needs to be with Backend team help
Removed

2023-09-07 22:48 UTC, m62534 approved these changes

2023-09-08 00:02 UTC, SeanEmac requested changes

2023-09-08 00:02 UTC, SeanEmac commented on k8s-cluster/template-files/kraken-configmaps.template
> +      "isUploadFileToLocal": true,
```suggestion
      "isUploadFileToLocal": false,
```

2023-09-08 00:11 UTC, SeanEmac approved these changes
:rocket:

2023-09-08 02:20 UTC, merged